### ISSUE TITLE
以音素为粒度的训练

### ISSUE THREAD

**Issue by bigcash** [sailist/ASRFrame#2]
这样的尝试，作者你是否做过了？
是否有其他资料或者论文可以共享一下吗？
谢谢

**Comment by sailist** [comment]
不好意思回复晚了，我最近没有在做这方面的工作，我记得有一个wavenet 还是啥的是以音素为粒度的，我这里面好像有尝试过复现但好像失败了来着...这方面开源工作似乎不是很多
